#!/usr/bin/env bash
# Installs and configures nginx
# It also displays "Holberton School" when you do an HTTP GET request

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html > /dev/null
sudo service nginx start
curl 127.0.0.1
