#!/usr/bin/env bash
# Installs and configures nginx
# It also displays "Holberton School" when you do an HTTP GET request

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx start
curl 127.0.0.1
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=-GEHyAfV4OI permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
