#!/usr/bin/env bash
# Turns out, the default in sites-enabled tried to connect to port 8080!
# Fix: Delete the default in .../sites-enabled/ and replace it with a symbolic link of the default file in .../sites-available

sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
