#!/usr/bin/env bash
# Creates a new user called 'nginx', which will have all necesary permissions required to run nginx.
pkill apache2
setfacl -m u:nginx:rwx -R /var/log/nginx/ /run/ /etc/nginx/ /usr/sbin/nginx /etc/init.d/nginx
sed -i "s/listen [0-9]\{1,\}/listen 8080/" /etc/nginx/sites-available/default
sed -i "s/listen \[::]\:[0-9]\{1,\}/listen [::]:8080/" /etc/nginx/sites-available/default
sudo --user=nginx /usr/sbin/nginx
